name: AmazingDailys
version: 1.0.0
author: Zephyrhz
main: zephy\daily\Loader
api: 5.0.0

permissions: 
    amazingdailys.default:
       default: true
    amazingdailys.op:
       default: op
